// Dicionário com as siglas e as estações associadas
var siglasEstacoes = {
    "ADABR": "ADA BR",
    "AJU": "AJU IT",
    "AMRHZ": "AMR HZ",
    "ANSGC": "ANS GC",
    "APSNT": "APS NT",
    "APUTL": "APU TL",
    "ARC": "Não consta roteadores cadastrados data de verificação 20/04/2023",
    "ARCHZ": "ARC HZ",
    "ARQARN": "ARQ ARN",
    "ATL": "Não consta roteadores cadastrados data de verificação 20/04/2023",
    "BERT0D": "BER T0D",
    "BERT0DW": "BERT 0DW",
    "BET0HH": "BET 0HH",
    "BGEACM": "BGE ACM",
    "BGP0AO": "BGP 0AO",
    "BGVEMD": "BGV EMD",
    "BHE": "BHE ES",
    "BHEES": "BHE ES",
    "BRUAL": "BRU AL",
    "BRUTS": "BRU TS",
    "BSA": "BSA SU",
    "BSASU": "BSA SU",
    "BSAGC": "BSA GC",
    "BSASN": "BSA SN",
    "BSATX": "BSA TX",
    "BTUTV": "BTU TV",
    "BVA": "BVA AB",
    "BVAAB": "BVA AB",
    "CANNET": "CAN NET",
    "CAS": "CAS BC",
    "CASBC": "CAS BC",
    "CASNS": "CAS NS",
    "CASQB": "CAS QB",
    "CASTS": "CAS TS",
    "CAS2FJ": "CAS 2FJ",
    "CBA": "CBA MC",
    "CBAMC": "CBA MC",
    "CBAAL": "CBA AL",
    "CCOCS": "CCO CS",
    "CEM": "CEM EP",
    "CGE0FE": "CGE 0FE",
    "CIM": "CIM BA",
    "CIMBA": "CIM BA",
    "CPE": "CPE CM",
    "CPEJM": "CPE JM",
    "CPS": "CPS CL",
    "CPSCL": "CPS CL",
    "CRUCJV": "CRU CJV",
    "CSCTE": "CSC TE",
    "CSCTV": "CSC TV",
    "CSL": "CSL VS",
    "CSLVS": "CSL VS",
    "CSLNET": "CSL NET",
    "CSLTH": "CSL TH",
    "CTA": "CTA TF",
    "CTATF": "CTA TF",
    "CTACL": "CTA CL",
    "CTACL6": "CTA CL6",
    "CTAMC": "CTA MC",
    "CTAMR": "CTA MR",
    "CTANJ": "CTA NJ",
    "CTAXH": "CTA XH",
    "CTA0HF": "CTA 0HF",
    "CTA0LT": "CTA 0LT",
    "CUATV": "CUA TV",
    "CZAJV1": "CZA JV1",
    "DOSAB": "DOS AB",
    "DOSCS": "DOS CS",
    "DQXTB": "DQX TB",
    "DVLAPJ": "DVL APJ",
    "EBTCRT": "EBT CRT",
    "ERE0ET": "ERE 0ET",
    "FACFF": "FAC FF",
    "FLA": "FLA PV",
    "FLAPV": "FLA PV",
    "FLABC": "FLA BC",
    "FLAJN": "FLA JN",
    "FLAPFU": "FLA PFU",
    "FNS": "FNS PO",
    "FNSPO": "FNS PO",
    "FSA": "FSA GV",
    "FSAGV": "FSA GV",
    "FSACS5": "FSA CS5",
    "FSASC": "FSA SC",
    "FSASC5": "FSA SC5",
    "FSASM": "FSA SM",
    "GJANET": "GJA NET",
    "GNA": "GNA RD",
    "GNARD": "GNA RD",
    "GNAAME": "GNA AME",
    "GNAGC": "GNA GC",
    "GRPMA": "GRP MA",
    "GRPNT": "GRP NT",
    "GRS": "Não consta roteadores cadastrados data de verificação 20/04/2023",
    "GRSNET": "GRS NET",
    "GRS0WX": "GRS 0WX",
    "GVS": "GVS JK",
    "GVSJK": "GVS JK",
    "GVS0F6": "GVS 0F6",
    "IAI": "IAI 0HK",
    "IAI0HK": "IAI 0HK",
    "IDUGC": "IDU GC",
    "IGAVV": "IGA VV",
    "IIG0EZ": "IIG 0EZ",
    "ITUXN": "ITU XN",
    "JAIGC": "JAI GC",
    "JAUTV": "JAU TV",
    "JFA": "JFA JC",
    "JFA JC": "JFA JC",
    "JFAJZ": "JFA JZ",
    "JPA": "JPA TR",
    "JPATR": "JPA TR",
    "JPABG": "JPA BG",
    "JPALM": "JPA LM",
    "JVELN": "JVE LN",
    "JVEUQ8": "JVE UQ8",
    "KDKUF": "KDK UF",
    "LDA": "LDA PR",
    "LDAPR": "LDA PR",
    "LJODE": "LJO DE",
    "MBA": "MBA TM",
    "MBATM": "MBA TM",
    "MCE": "MCE CV",
    "MCECV": "MCE CV",
    "MCLDR": "MCL DR",   
    "MCO": "MCO MS",
    "MCOMS": "MCO MS",
    "MCOBJ": "MCO BJ",
    "MCO0FN": "MCO 0FN",
    "MCZNEW": "MCZ NEW",
    "MESQV2E": "MESQ V2E",
    "MGA": "MGA NM",
    "MGANM": "MGA NM",
    "MGAAN": "MGA AN",
    "MGACLA": "MGA CLA",
    "MGAZT": "MGA ZT",
    "MIAMP": "MIA MP",
    "MIANAP": "MIA NAP",
    "MIATV": "MIA TV",
    "MIA6": "Não consta roteadores cadastrados data de verificação 20/04/2023",
    "MNS": "MNS LM",
    "MNSLM": "MNS LM",
    "MNSHZ": "MNS HZ",
    "MPA": "MPA GG",
    "MPAGG": "MPA GG",
    "NHOLO": "NHO LO",
    "NRI": "NRI ITG",
    "NRIITG": "NRI ITG",
    "NTL": "NTL JU",
    "NTLJU": "NTL JU",
    "NTLBE": "NTL BE",
    "NYK": "Não consta roteadores cadastrados data de verificação 20/04/2023",
    "OCO": "OCO SA",
    "OCOSA": "OCO SA",
    "PAAGC": "PAA GC",
    "PAARO": "PAA RO",
    "PAARON": "PAA RON",
    "PAE": "PAE BV",
    "PAEBV": "PAE BV",
    "PAECL": "PAE CL",
    "PAEMF": "PAE MF",
    "PAENR": "PAE NR",
    "PAENT": "PAE NT",
    "PAETT": "PAE TT",
    "PASNET": "PAS NET",
    "PASPDR": "PAS PDR",
    "PBAWT": "PBA WT",
    "PGO RB": "PGO RB",
    "PGORB": "PGO RB",
    "PGOTL": "PGO TL",
    "PGOTV": "PGO TV",
    "PLTQN": "PLT QN",
    "PLTTF": "PLT TF",
    "PMJAT": "PMJ AT",
    "PMJSO": "PMJ SO",
    "PPEAT": "PPE AT",
    "PPETS": "PPE TS",
    "PTA": "PTA PL",
    "PTAPL": "PTA PL",
    "PTLQN": "PTL QN",
    "PTS": "Estação só consta PE dos circuitos da CLARO, neste caso, pode preencher somente: PTS",
    "PTS0F8": "PTS 0F8",
    "PVO": "PVO FQ",
    "PVOFQ": "PVO FQ",
    "RBO": "RBO RB",
    "RBORB": "RBO RB",
    "RBOAI": "RBO AI",
    "RCE": "RCE AM",
    "RCEAM": "RCE AM",
    "RCEAU": "RCE AU",
    "RCEBV": "RCE BV",
    "RCEEAC": "RCE EAC",
    "RJOAC": "RJO AC",
    "RJO": "RJO AM",
    "RJOAM": "RJO AM",
    "RJOAM13": "RJO AM13",
    "RJOAZ": "RJO AZ",
    "RJOEN": "RJO EN",
    "RJONBF": "RJO NBF",
    "RJONT0": "RJO NT0",
    "RJOST": "RJO ST",
    "RJO0TD": "RJO 0TD",
    "RJO0TF": "RJO 0TF",
    "RJO0TL": "RJO 0TL",
    "RJO1NX": "RJO 1NX",
    "RJO2AT": "RJO 2AT",
    "RJO4CL": "RJO 4CL",
    "ROIMD": "ROI MD",
    "ROI0JY": "ROI 0JY",
    "RPO": "RPO TB",
    "RPOTB": "RPO TB",
    "RPONZ": "RPO NZ",
    "RPOTZ": "RPO TZ",
    "RSDVV": "RSD VV",
    "SBO": "SBO JP",
    "SBOJP": "SBO JP",
    "SCLNT": "SCL NT",
    "SCRTV": "SCR TV",
    "SDR": "SDR RC",
    "SDRRC": "SDR RC",
    "SDRDCN": "SDR DCN",
    "SDRIT": "SDR IT",
    "SDRZX": "SDR ZX",
    "SEANET": "SEA NET",
    "SJC": "SJC EB",
    "SJCEB": "SJC EB",
    "SJCCN": "SJC CN",
    "SJCEZ": "SJC EZ",
    "SLA0H3": "SLA 0H3",
    "SLOOCE": "SLO OCE",
    "SLS": "SLS US",
    "SLSUS": "SLS US",
    "SMACLA": "SMA CLA",
    "SMATT": "SMA TT",
    "SNE": "SNE JC",
    "SNEJC": "SNE JC",
    "SOC": "SOC PH",
    "SOCPH": "SOC PH",
    "SOCRN": "SOC RN",
    "SOONS": "SOO NS",
    "SPO": "SPO IG",
    "SPOIG": "SPO IG",
    "SPOJK": "SPO JK",
    "SPOLP": "SPO LP",
    "SPOMB": "SPO MB",
    "SPOMPU": "SPO MPU",
    "SPOOPT": "SPO OPT",
    "SPOPH": "SPO PH",
    "SPO0CG": "SPO 0CG",
    "SPO0JG": "SPO 0JG",
    "SPO0KA": "SPO 0KA",
    "SPO0PE": "SPO 0PE",
    "SPO1QR": "SPO 1QR",
    "SRM": "SRM SP",
    "SRMSP": "SRM SP",
    "SRR": "Não consta roteadores cadastrados data de verificação 20/04/2023",
    "SRRQN": "SRR QN",
    "SRRTE": "SRR TE",
    "STS": "STS WL",
    "STSWL": "STS WL",
    "STSTB": "STS TB",
    "STZTV": "STZ TV",
    "SVENEW": "SVE NEW",
    "SVEVP": "SVE VP",
    "TANGBR": "TAN GBR",
    "TOTJR": "TOT JR",
    "TRL0E8": "TRL 0E8",
    "TSA": "TSA AN",
    "TSAAN": "TSA AN",
    "TSAMF": "TSA MF",
    "TTESC": "TTE SC",
    "UGN0EG": "UGN 0EG", 
    "ULA": "ULA MA",
    "ULAMA": "ULA MA",
    "URAFR": "URA FR",
    "VCANET": "VCA NET",
    "VCAVC": "VCA VC",
    "VGAJGP": "VGA JGP",
    "VGATG": "VGA TG",
    "VOSTV": "VOS TV",
    "VRD": "VRD SC",
    "VRDSC": "VRD SC",
    "VTA": "VTA JM",
    "VTAJM": "VTA JM",
    "VTAGK": "VTA GK",
    "VTAVA0": "VTA VA0",
    // Adicionar todas as siglas e estações aqui
};

function buscarEstacao() {
    var sigla = document.getElementById("sigla").value.toUpperCase(); // Obtém a sigla inserida pelo usuário em letras maiúsculas
    var estacaoLabel = document.getElementById("resultado"); // Obtém o elemento HTML onde será exibido o resultado

    // Verifica se a sigla existe no dicionário
    if (siglasEstacoes.hasOwnProperty(sigla)) {
        var estacao = siglasEstacoes[sigla]; // Obtém o nome da estação correspondente à sigla
        estacaoLabel.textContent = "Estação de acesso é: " + estacao; // Exibe o resultado no elemento HTML
    } else {
            estacaoLabel.textContent = "Sigla não encontrada"; // Exibe mensagem de erro caso a sigla não seja encontrada
    }
}

function limparDados() {
    document.getElementById("sigla").value = ""; // Limpa o campo de input
    document.getElementById("resultado").textContent = ""; // Limpa o resultado anterior
    }

    document.getElementById("sigla").addEventListener("keydown", function(event) {
        if (event.key === "Enter") {
            event.preventDefault(); // Impede o comportamento padrão do Enter de inserir uma quebra de linha
            buscarEstacao();
        }
    });

    document.addEventListener("keydown", function(event) {
    if (event.key === "Escape") {
    event.preventDefault(); // Impede o comportamento padrão do ESC de fechar a janela
    limparDados();
    }
});
